### ISSUE TITLE
sslh in transparent mode and docker

### ISSUE THREAD

**Issue by Flow86** [yrutschle/sslh#276]
Hi,

I currently try to have a setup like this:

Host (myhost.example.com):
- two network interfaces: lan and wan (nat)
- running sslh in transparent mode on port 443, forwarding ssh to 22 and https to 8443
- running a local http(s) server
- running dockerd

Container on docker@Host:
   - tries to access https://myhost.example.com:443 via ipv4

my ipv6 setup is working fine, but the ipv4 setup is broken. I think it has something to do with the iptables rules there

sslh config:
```
# This is a basic configuration file that should provide
# sensible values for "standard" setup.

verbose: false;
foreground: false;
inetd: false;
numeric: false;
transparent: true;
timeout: 2;
user: "sslh";
pidfile: "/var/run/sslh/sslh.pid";
#chroot: "/var/empty";

syslog_facility: "auth";

listen:
(
    { host: "0.0.0.0"; port: "443"; keepalive: true; },
    { host: "2001:%SNIPPED%"; port: "443"; keepalive: true; }
);

protocols:
(
    { name: "ssh"; service: "ssh"; host: "sslh"; port: "995"; keepalive: true; fork: true; tfo_ok: true },

    { name: "tls"; host: "sslh"; port: "8443"; log_level: 0; tfo_ok: true },
    { name: "anyprot"; host: "sslh"; port: "8443"; tfo_ok: true }
);
```

in /etc/hosts for "sslh" both the ipv4 (local lan) and ipv6 (global) address are specified.

sslh (on host ) output:
```
# host myhost.example.com
myhost.example.com has address %WANIP%
# sslh -F -v 3 -f
connecting to myhost.example.com:8443 family 10 len 28
flushing deferred data to fd 3
client socket closed
connection closed down
```

container:
```
# host myhost.example.com
myhost.example.com has address %WANIP%
# openssl s_client -4 -connect myhost.example.com:443
CONNECTED(00000003)
```

it can connect to the host, but does not get any data back - probably some routing error in the iptables on the host?

I'm using ufw with some custom docker rule extensions:

```
# sysctl -w net.ipv4.conf.default.route_localnet=1
# sysctl -w net.ipv4.conf.all.route_localnet=1
```

```
# Generated by iptables-save v1.8.3 on Mon Aug 10 11:27:59 2020
*mangle
:PREROUTING ACCEPT [25871328:23302466728]
:INPUT ACCEPT [3753734:4693476301]
:FORWARD ACCEPT [22118426:18609047217]
:OUTPUT ACCEPT [3249921:3995064195]
:POSTROUTING ACCEPT [25367210:22604130362]
-A OUTPUT ! -o lo -p tcp -m connmark --mark 0x1/0xf -j CONNMARK --restore-mark --nfmask 0xf --ctmask 0xf
-A POSTROUTING -s 127.0.0.0/8 ! -o lo -j DROP
COMMIT
# Completed on Mon Aug 10 11:27:59 2020
# Generated by iptables-save v1.8.3 on Mon Aug 10 11:27:59 2020
*raw
:PREROUTING ACCEPT [25871342:23302467472]
:OUTPUT ACCEPT [3249936:3995065827]
-A PREROUTING -d 127.0.0.0/8 ! -i lo -j DROP
COMMIT
# Completed on Mon Aug 10 11:27:59 2020
# Generated by iptables-save v1.8.3 on Mon Aug 10 11:27:59 2020
*filter
:INPUT DROP [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [1708:88336]
:DOCKER - [0:0]
:DOCKER-ISOLATION-STAGE-1 - [0:0]
:DOCKER-ISOLATION-STAGE-2 - [0:0]
:DOCKER-USER - [0:0]
:ufw-after-forward - [0:0]
:ufw-after-input - [0:0]
:ufw-after-logging-forward - [0:0]
:ufw-after-logging-input - [0:0]
:ufw-after-logging-output - [0:0]
:ufw-after-output - [0:0]
:ufw-before-forward - [0:0]
:ufw-before-input - [0:0]
:ufw-before-logging-forward - [0:0]
:ufw-before-logging-input - [0:0]
:ufw-before-logging-output - [0:0]
:ufw-before-output - [0:0]
:ufw-logging-allow - [0:0]
:ufw-logging-deny - [0:0]
:ufw-logging-route-deny - [0:0]
:ufw-not-local - [0:0]
:ufw-reject-forward - [0:0]
:ufw-reject-input - [0:0]
:ufw-reject-output - [0:0]
:ufw-skip-to-policy-forward - [0:0]
:ufw-skip-to-policy-input - [0:0]
:ufw-skip-to-policy-output - [0:0]
:ufw-track-forward - [0:0]
:ufw-track-input - [0:0]
:ufw-track-output - [0:0]
:ufw-user-forward - [0:0]
:ufw-user-input - [0:0]
:ufw-user-limit - [0:0]
:ufw-user-limit-accept - [0:0]
:ufw-user-logging-forward - [0:0]
:ufw-user-logging-input - [0:0]
:ufw-user-logging-output - [0:0]
:ufw-user-output - [0:0]
-A INPUT -j ufw-before-logging-input
-A INPUT -j ufw-before-input
-A INPUT -j ufw-after-input
-A INPUT -j ufw-after-logging-input
-A INPUT -j ufw-reject-input
-A INPUT -j ufw-track-input
-A FORWARD -j DOCKER-USER
-A FORWARD -j DOCKER-ISOLATION-STAGE-1
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -j ufw-before-logging-forward
-A FORWARD -j ufw-before-forward
-A FORWARD -j ufw-after-forward
-A FORWARD -j ufw-after-logging-forward
-A FORWARD -j ufw-reject-forward
-A FORWARD -j ufw-track-forward
-A OUTPUT -j ufw-before-logging-output
-A OUTPUT -j ufw-before-output
-A OUTPUT -j ufw-after-output
-A OUTPUT -j ufw-after-logging-output
-A OUTPUT -j ufw-reject-output
-A OUTPUT -j ufw-track-output
-A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -j RETURN
-A DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP
-A DOCKER-ISOLATION-STAGE-2 -j RETURN
-A DOCKER-USER -s 172.16.0.0/12 -j RETURN
-A DOCKER-USER -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A DOCKER-USER -m conntrack --ctstate INVALID -j DROP
-A DOCKER-USER -p udp -m udp --sport 53 --dport 1024:65535 -j RETURN
-A DOCKER-USER ! -i br+ -o br+ -j ufw-user-input
-A DOCKER-USER ! -i br+ -o br+ -j ufw-logging-route-deny
-A DOCKER-USER ! -i br+ -o br+ -j REJECT --reject-with icmp-port-unreachable
-A DOCKER-USER -j RETURN
-A ufw-after-input -p udp -m udp --dport 137 -j ufw-skip-to-policy-input
-A ufw-after-input -p udp -m udp --dport 138 -j ufw-skip-to-policy-input
-A ufw-after-input -p tcp -m tcp --dport 139 -j ufw-skip-to-policy-input
-A ufw-after-input -p tcp -m tcp --dport 445 -j ufw-skip-to-policy-input
-A ufw-after-input -p udp -m udp --dport 67 -j ufw-skip-to-policy-input
-A ufw-after-input -p udp -m udp --dport 68 -j ufw-skip-to-policy-input
-A ufw-after-input -m addrtype --dst-type BROADCAST -j ufw-skip-to-policy-input
-A ufw-before-forward -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A ufw-before-forward -p icmp -m icmp --icmp-type 3 -j ACCEPT
-A ufw-before-forward -p icmp -m icmp --icmp-type 11 -j ACCEPT
-A ufw-before-forward -p icmp -m icmp --icmp-type 12 -j ACCEPT
-A ufw-before-forward -p icmp -m icmp --icmp-type 8 -j ACCEPT
-A ufw-before-forward -j ufw-user-forward
-A ufw-before-input -i lo -j ACCEPT
-A ufw-before-input -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A ufw-before-input -m conntrack --ctstate INVALID -j ufw-logging-deny
-A ufw-before-input -m conntrack --ctstate INVALID -j DROP
-A ufw-before-input -p icmp -m icmp --icmp-type 3 -j ACCEPT
-A ufw-before-input -p icmp -m icmp --icmp-type 11 -j ACCEPT
-A ufw-before-input -p icmp -m icmp --icmp-type 12 -j ACCEPT
-A ufw-before-input -p icmp -m icmp --icmp-type 8 -j ACCEPT
-A ufw-before-input -p udp -m udp --sport 67 --dport 68 -j ACCEPT
-A ufw-before-input -j ufw-not-local
-A ufw-before-input -d 224.0.0.251/32 -p udp -m udp --dport 5353 -j ACCEPT
-A ufw-before-input -d 239.255.255.250/32 -p udp -m udp --dport 1900 -j ACCEPT
-A ufw-before-input -j ufw-user-input
-A ufw-before-output -o lo -j ACCEPT
-A ufw-before-output -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A ufw-before-output -j ufw-user-output
-A ufw-logging-route-deny -m limit --limit 3/min --limit-burst 10 -j LOG --log-prefix "[UFW ROUTE BLOCK] "
-A ufw-not-local -m addrtype --dst-type LOCAL -j RETURN
-A ufw-not-local -m addrtype --dst-type MULTICAST -j RETURN
-A ufw-not-local -m addrtype --dst-type BROADCAST -j RETURN
-A ufw-not-local -m limit --limit 3/min --limit-burst 10 -j ufw-logging-deny
-A ufw-not-local -j DROP
-A ufw-reject-input -j REJECT --reject-with icmp-port-unreachable
-A ufw-skip-to-policy-forward -j ACCEPT
-A ufw-skip-to-policy-input -j REJECT --reject-with icmp-port-unreachable
-A ufw-skip-to-policy-output -j ACCEPT
-A ufw-track-forward -p tcp -m conntrack --ctstate NEW -j ACCEPT
-A ufw-track-forward -p udp -m conntrack --ctstate NEW -j ACCEPT
-A ufw-track-output -p tcp -m conntrack --ctstate NEW -j ACCEPT
-A ufw-track-output -p udp -m conntrack --ctstate NEW -j ACCEPT
-A ufw-user-limit -j REJECT --reject-with icmp-port-unreachable
-A ufw-user-limit-accept -j ACCEPT
-A ufw-user-logging-forward -j RETURN
-A ufw-user-logging-input -j RETURN
-A ufw-user-logging-output -j RETURN
COMMIT
# Completed on Mon Aug 10 11:27:59 2020
# Generated by iptables-save v1.8.3 on Mon Aug 10 11:27:59 2020
*nat
:PREROUTING ACCEPT [4790:538426]
:INPUT ACCEPT [2100:143821]
:OUTPUT ACCEPT [1768:125187]
:POSTROUTING ACCEPT [2937:178843]
:DOCKER - [0:0]
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT -p tcp -m owner --uid-owner 106 -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -j CONNMARK --set-xmark 0x1/0xf
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-A POSTROUTING -o wan0 -j MASQUERADE
-A DOCKER -i docker0 -j RETURN
COMMIT
# Completed on Mon Aug 10 11:27:59 2020
```

also the fwmark is set:
```
/sbin/ip rule add fwmark 0x1 lookup 100 || true
/sbin/ip route add local 0.0.0.0/0 dev lo table 100 || true
```

from every other host (localhost and on lan or on wan) the transparent mode works, but not from inside the container(s)

What do I miss there?
Thank you!

**Comment by SBado** [comment]
I'm facing the exact same problem. @Flow86 have you ever found a solution?

**Comment by Flow86** [comment]
Hi,
I'm sorry but I did not.

I changed my network architecture in the mean time so that I stopped using sslh

**Comment by f-vt** [comment]
Hi,

I have actually found a way to make it works in transparent mode, inspired from this link: [https://superuser.com/questions/1326592/how-to-set-up-sslhs-transparent-mode-in-a-docker-environment](https://superuser.com/questions/1326592/how-to-set-up-sslhs-transparent-mode-in-a-docker-environment)
SSLH running on HOST and forwarding TLS to DOCKER container, and SSH on the host.

I do not use the --publish option of docker which conflicts with SSLH rules, except for the 80 port which is still accessed directly, not through SSLH.
My "traefik" (reverse proxy I want to have behind SSLH) docker service is put on a dedicated overlay (should work with bridge also) network called "proxy" where it is alone, and in DNRR mode so that it will not be put behind a docker VIP (we don't want that IP appear only in the logs...).
So, as it is alone in the "proxy" network it will always take the .2 IP address (if you wish to use hostname: [https://www.linkedin.com/pulse/learn-how-access-docker-container-its-name-from-host-renato-rodrigues](https://www.linkedin.com/pulse/learn-how-access-docker-container-its-name-from-host-renato-rodrigues) ).

Traefik is configured to listen on ports 80 and 443, having 443 is not a issue and will not conflicts as it it not published on the host by docker but stay isolated in "proxy" network. And it must not be added to the iptables SSLH rules.

I use the docker_gwbridge to access it from the host (added a route to this network though docker_gwbridge IP on the host).

- My traefik docker configuration:
  ```yaml
  services:
    traefik:
      # The official v2.0 Traefik docker image
      image: traefik:latest
      # 2 replicas as critical service (needs to be in swarm mode)
      deploy:
        # to see real IP in logs: Mode global: one (and only one) service per node); to use with HOST networking (so that ports exposed on host through bridge network direclty, bypassing mesh overlay
        mode: global
        # for not putting it behind VIP and then seeing real client IPs
        endpoint_mode: dnsrr
        placement:
          constraints:
            # Traefik instances needs to be scheduled on a manager node to get labels (this reduces availability for example in case the node fails (we'll need to wait for a redeploy on another node) but no other option yet)
            - "node.role==manager"
        restart_policy:
          condition: any
        update_config:
          parallelism: 1
          delay: 5s
          order: start-first
          monitor: 30s
          failure_action: rollback
      # Configure networks for traffic to endpoint to RP
      networks:
        - proxy
        - web_priv_services
        - web_devops_tools
        - security_services
      # Expose following ports to HOST IP (clients to RP)
      ports:
        # The HTTP port / HOST mode to see real IP in logs (to bypass overlay/mesh; combined with global deployment instruction)
        - target: 80
          published: 80
          protocol: tcp
          mode: host
        # HTTPS exposure handled by SSLH, and forwarded to container private ip in the "proxy" vxlan (added route on host using docker_gwbridge IP)
      environment:
        - "GANDIV5_API_KEY_FILE=/run/secrets/gandiv5_api_key"
        - LEGO_DISABLE_CNAME_SUPPORT=true # https://community.traefik.io/t/suddenly-experiencing-error-400-invalid-domain-errors-with-le-certs/16366/2 - IF YOU HAVE A WILDCARD CNAME for your DNS Zone - LEGO (backend program used by traefik for adding TXT entries through DNS provider API for automating letsencrypt DNS Challenge) can't check cname if a wildcard is present... Need to disable this  
        - TZ=Europe/Paris
        #- PUID=33 # Not handled by traefik container
        #- PGID=33 # Not handled by traefik container
      command:
        - '--api.dashboard=true' 
        #- '--api.insecure=true' don't needed, it exposes api on 8080, but we are using RP to api@internal not 8080.
        # Logs for Crowdsec
        - '--accesslog=true'
        # Docker provider
        - '--providers.docker'
        - '--providers.docker.endpoint=unix:///var/run/docker.sock'
        - '--providers.docker.watch=true'
        - '--providers.docker.exposedByDefault=false' # Warning: you needs to explicitely set "traefik.enable" flag label to true
        - '--providers.docker.swarmmode=false' # at the moment we use the docker socket, no need to use swarm mode
        # File provider
        - '--providers.file.directory=/traefik-dynamic-configs/'
        - '--providers.file.watch=true'
        # Entrypoints config
        - '--entrypoints.http=true'
        - '--entryPoints.http.address=:80'
        - '--entrypoints.https=true'
        - '--entryPoints.https.address=:443'
        # Entrypoints - http to https
        - '--entrypoints.http.http.redirections.entrypoint.to=https'
        - '--entrypoints.http.http.redirections.entrypoint.scheme=https'
        # CERT Resolver
        - '--certificatesresolvers.skyfvtdnschallenge.acme.email=XXXXXXX@XXXX.XXX'
        #- '--certificatesresolvers.skyfvtdnschallenge.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory' # letsencrypt staging/testing when needs debugging to not reach letsencrypt rate limit
        - '--certificatesresolvers.skyfvtdnschallenge.acme.storage=/letsencrypt/acme.json'
        - '--certificatesresolvers.skyfvtdnschallenge.acme.dnschallenge=true'
        - '--certificatesresolvers.skyfvtdnschallenge.acme.dnschallenge.provider=gandiv5'
        - '--certificatesresolvers.skyfvtdnschallenge.acme.dnschallenge.resolvers=217.70.177.40:53,173.246.100.219:53' # IMPORTANT: Put some Gandi's NS IP there. If not, letsencypt will have to wait A LOT OF TIME the DNS propagation (DNS challenge use in our case gandi API to create an entry in our DNS zone at our provider to validate ownership)
        # Enabling WAF module
        - '--experimental.plugins.traefik-modsecurity-plugin.modulename=github.com/madebymode/traefik-modsecurity-plugin'
        - '--experimental.plugins.traefik-modsecurity-plugin.version=v1.4.5'
      volumes:
        # Traefik certificate storage
        - traefik_letsencrypt:/letsencrypt/
        # Traefik dynamic config files (profider.file.directory)
        - traefik_dynconfig:/traefik-dynamic-configs/:ro
        # So that Traefik can listen to the Docker events
        - /var/run/docker.sock:/var/run/docker.sock:ro
      secrets:
        - gandiv5_api_key  
      labels:
        # GLOBAL - Auth
        - "traefik.http.middlewares.auth.basicauth.users=XXXXX:XXXXX" # use htpasswd to generate, double the $ signs
        # GLOBAL - Headers
        # Commented cause better conf below - 'traefik.http.middlewares.HSTS.headers.customresponseheaders.Strict-Transport-Security="max-age=6307200; includeSubDomains; preload"'
        - "traefik.http.middlewares.security-and-proxy-headers.headers.accessControlAllowOriginList=*"
        - "traefik.http.middlewares.security-and-proxy-headers.headers.AccessControlMaxAge=100"
        - "traefik.http.middlewares.security-and-proxy-headers.headers.BrowserXssFilter=true"
        - "traefik.http.middlewares.security-and-proxy-headers.headers.ContentTypeNosniff=true"
        - "traefik.http.middlewares.security-and-proxy-headers.headers.ForceSTSHeader=true"
        - "traefik.http.middlewares.security-and-proxy-headers.headers.FrameDeny=true"
        - "traefik.http.middlewares.security-and-proxy-headers.headers.SSLRedirect=true"
        - "traefik.http.middlewares.security-and-proxy-headers.headers.STSIncludeSubdomains=true"
        - "traefik.http.middlewares.security-and-proxy-headers.headers.STSPreload=true"
        - "traefik.http.middlewares.security-and-proxy-headers.headers.STSSeconds=63072000"
        - "traefik.http.middlewares.security-and-proxy-headers.headers.CustomFrameOptionsValue=SAMEORIGIN"
        - "traefik.http.middlewares.security-and-proxy-headers.headers.referrerPolicy=same-origin"
        #- "traefik.http.middlewares.security-and-proxy-headers.headers.hostsProxyHeaders=X-Forwarded-Host"
        #- "traefik.http.middlewares.security-and-proxy-headers.headers.sslProxyHeaders.X-Forwarded-Proto=https"
        # GLOBAL - Other
        - "traefik.http.middlewares.other.buffering.maxRequestBodyBytes=0"
        - "traefik.http.middlewares.other.buffering.memRequestBodyBytes=1000000000"
        - "traefik.http.middlewares.other.buffering.maxResponseBodyBytes=0"
        - "traefik.http.middlewares.other.buffering.memResponseBodyBytes=1000000000"
        - "traefik.http.middlewares.other.compress=false"
        # Endpoint Config
        - "traefik.enable=true"
        - "traefik.http.routers.api.entrypoints=https"
        - "traefik.http.routers.api.rule=Host(`XXXXXXXXXXX.XXX`)"
        - "traefik.http.routers.api.tls=true"
        - 'traefik.http.routers.api.tls.options=modern@file'
        - "traefik.http.routers.api.middlewares=auth,security-and-proxy-headers"
        - "traefik.http.routers.api.service=api@internal" # Assign api@internal who is pregenerated by traefik for itself to the api router, so nothing to configure for this, rewrites for api, etc. already defined.
        - "traefik.http.routers.api.tls.certresolver=xxxxxxxxx"
        - "traefik.http.routers.api.tls.domains[0].main=XXXXXXXXXXX.XXX"
        - "traefik.http.routers.api.tls.domains[0].sans=*.XXXXXXXXXXX.XXX"  # this wildcard cert will then be applied to all sites matching it
        # WAF enable (This is a very simple plugin that proxies the query to the owasp/modsecurity apache container, and checks in its answer if it has detected something in the query (>400 response) or not). Set max body size to inspect to 1GB.
        - traefik.http.middlewares.waf.plugin.traefik-modsecurity-plugin.modSecurityUrl=http://waf:80
        - traefik.http.middlewares.waf.plugin.traefik-modsecurity-plugin.maxBodySize=1073741824
        - traefik.http.middlewares.waf.plugin.traefik-modsecurity-plugin.cacheEnabled=true
  ```
