### ISSUE TITLE
Any help with config for this scenario?

### ISSUE THREAD

**Issue by essoojay** [yrutschle/sslh#403]
Am a complete noob whenit comes to this, and i want to know if its possible to implement sslh for below situation:
And if possible help with a config template.

NOTE, i have tried with on-timeout anyprot but could not get it to work ..

Share port 443 ssl with:
V2ray
sstp vpn

And Port 80 with:
http proxy
ohpserver

Thanks

**Comment by ljluestc** [comment]
```
# Listen for incoming traffic on port 443
listen:
  - protocol: tcp
    host: 0.0.0.0
    port: 443
    on-timeout: anyproto
    timeout: 1

# Define the services to forward traffic based on the protocol
services:
  - name: v2ray
    host: localhost
    port: 10000
    protocol: tcp
    timeout: 5
    no-delay: false
    skip-probe: true
    service: tls

  - name: sstp_vpn
    host: localhost
    port: 20000
    protocol: tcp
    timeout: 5
    no-delay: false
    skip-probe: true
    service: tls

# Listen for incoming traffic on port 80
listen:
  - protocol: tcp
    host: 0.0.0.0
    port: 80
    on-timeout: anyproto
    timeout: 1

# Define the services to forward traffic based on the protocol
services:
  - name: http_proxy
    host: localhost
    port: 30000
    protocol: tcp
    timeout: 5
    no-delay: false
    skip-probe: true

  - name: ohp_server
    host: localhost
    port: 40000
    protocol: tcp
    timeout: 5
    no-delay: false
    skip-probe: true

```

**Comment by essoojay** [comment]
> ```
> # Listen for incoming traffic on port 443
> listen:
>   - protocol: tcp
>     host: 0.0.0.0
>     port: 443
>     on-timeout: anyproto
>     timeout: 1
> 
> # Define the services to forward traffic based on the protocol
> services:
>   - name: v2ray
>     host: localhost
>     port: 10000
>     protocol: tcp
>     timeout: 5
>     no-delay: false
>     skip-probe: true
>     service: tls
> 
>   - name: sstp_vpn
>     host: localhost
>     port: 20000
>     protocol: tcp
>     timeout: 5
>     no-delay: false
>     skip-probe: true
>     service: tls
> 
> # Listen for incoming traffic on port 80
> listen:
>   - protocol: tcp
>     host: 0.0.0.0
>     port: 80
>     on-timeout: anyproto
>     timeout: 1
> 
> # Define the services to forward traffic based on the protocol
> services:
>   - name: http_proxy
>     host: localhost
>     port: 30000
>     protocol: tcp
>     timeout: 5
>     no-delay: false
>     skip-probe: true
> 
>   - name: ohp_server
>     host: localhost
>     port: 40000
>     protocol: tcp
>     timeout: 5
>     no-delay: false
>     skip-probe: true
> ```




Thank you for your help.   I tried as .cfg and i got syntax error


root@localhost:~# sslh -F /etc/sslh/sslh.cfg
/etc/sslh/sslh.cfg:3:syntax error

what could be wrong..

**Comment by ljluestc** [comment]
```
# Listen for incoming traffic on port 443
listen:
  - protocol: tcp
    host: 0.0.0.0
    port: 443
    on-timeout: anyproto
    timeout: 1

# Define the services to forward traffic based on the protocol
services:
  - name: v2ray
    host: localhost
    port: 10000
    protocol: tcp
    timeout: 5
    no-delay: false
    skip-probe: true
    service: tls

  - name: sstp_vpn
    host: localhost
    port: 20000
    protocol: tcp
    timeout: 5
    no-delay: false
    skip-probe: true
    service: tls

# Listen for incoming traffic on port 80
listen:
  - protocol: tcp
    host: 0.0.0.0
    port: 80
    on-timeout: anyproto
    timeout: 1

# Define the services to forward traffic based on the protocol
services:
  - name: http_proxy
    host: localhost
    port: 30000
    protocol: tcp
    timeout: 5
    no-delay: false
    skip-probe: true

  - name: ohp_server
    host: localhost
    port: 40000
    protocol: tcp
    timeout: 5
    no-delay: false
    skip-probe: true

```
