### ISSUE TITLE
modprobe: can't change directory to '/lib/modules': No such file or directory

### ISSUE THREAD

**Issue by scmanjarrez** [yrutschle/sslh#409]
Hi,
I'm receiving this error, should I care about it? Or can be dismissed?
This is my current configuration

```
version: "3"                                                                                                                                                                                                       
                                                                                                                                                                                                                   
services:                                                                                                                                                                                                          
  sslh:                                                                                                                                                                                                            
    build: https://github.com/yrutschle/sslh.git                                                                                                                                                                   
    container_name: sslh                                                                                                                                                                                           
    environment:                                                                                                                                                                                                   
      - TZ="Europe/Madrid"                                                                                                                                                                                         
    cap_add:                                                                                                                                                                                                       
      - NET_ADMIN                                                                                                                                                                                                  
      - NET_RAW                                                                                                                                                                                                    
      - NET_BIND_SERVICE                                                                                                                                                                                           
    # must be set manually                                                                                                                                                                                         
    #sysctls:                                                                                                                                                                                                      
    #  - net.ipv4.conf.default.route_localnet=1                                                                                                                                                                    
    #  - net.ipv4.conf.all.route_localnet=1                                                                                                                                                                        
    command: --transparent --foreground --listen=0.0.0.0:443 --tls=localhost:8080 --openvpn=localhost:8009 --ssh=localhost:22                                                                                      
    network_mode: host                                                                                                                                                                                             
    restart: always  
```

```
❯ sudo sysctl net.ipv4.conf.all.route_localnet
net.ipv4.conf.all.route_localnet = 1
❯ sudo sysctl net.ipv4.conf.default.route_localnet
net.ipv4.conf.default.route_localnet = 1
```

Full log:
```
sslh  | + iptables -t raw -A PREROUTING '!' -i lo -d 127.0.0.0/8 -j DROP                                                                                                                                           
sslh  | --transparent flag is set                                                                                                                                                                                  
sslh  | Configuring iptables and routing...                                                                                                                                                                        
sslh  | + iptables -t mangle -A POSTROUTING '!' -o lo -s 127.0.0.0/8 -j DROP                                                                                                                                       
sslh  | + iptables -t nat -A OUTPUT -m owner --uid-owner sslh -p tcp --tcp-flags FIN,SYN,RST,ACK SYN -j CONNMARK --set-xmark 0x01/0x0f                                                                             
sslh  | + iptables -t mangle -A OUTPUT '!' -o lo -p tcp -m connmark --mark 0x01/0x0f -j CONNMARK --restore-mark --mask 0x0f                                                                                        
sslh  | + ip rule add fwmark 0x1 lookup 100                                                                                                                                                                        
sslh  | + ip route add local 0.0.0.0/0 dev lo table 100                                                                                                                                                            
sslh  | + cat /proc/sys/net/ipv6/conf/all/disable_ipv6                                                                                                                                                             
sslh  | + '[' 0 -eq 0 ]                                                                                                                                                                                            
sslh  | + ip6tables -t raw -A PREROUTING '!' -i lo -d ::1/128 -j DROP                                                                                                                                              
sslh  | modprobe: can't change directory to '/lib/modules': No such file or directory                                                                                                                              
sslh  | ip6tables v1.8.9 (legacy): can't initialize ip6tables table `raw': Table does not exist (do you need to insmod?)                                                                                           
sslh  | Perhaps ip6tables or your kernel needs to be upgraded.                                                                                                                                                     
sslh  | + ip6tables -t mangle -A POSTROUTING '!' -o lo -s ::1/128 -j DROP                                                                                                                                          
sslh  | modprobe: can't change directory to '/lib/modules': No such file or directory                                                                                                                              
sslh  | ip6tables v1.8.9 (legacy): can't initialize ip6tables table `mangle': Table does not exist (do you need to insmod?)                                                                                        
sslh  | Perhaps ip6tables or your kernel needs to be upgraded.                                                                                                                                                     
sslh  | + ip6tables -t nat -A OUTPUT -m owner --uid-owner sslh -p tcp --tcp-flags FIN,SYN,RST,ACK SYN -j CONNMARK --set-xmark 0x01/0x0f                                                                            
sslh  | modprobe: can't change directory to '/lib/modules': No such file or directory                                                                                                                              
sslh  | modprobe: can't change directory to '/lib/modules': No such file or directory
sslh  | modprobe: can't change directory to '/lib/modules': No such file or directory
sslh  | modprobe: can't change directory to '/lib/modules': No such file or directory
sslh  | modprobe: can't change directory to '/lib/modules': No such file or directory
sslh  | modprobe: can't change directory to '/lib/modules': No such file or directory
sslh  | ip6tables v1.8.9 (legacy): unknown option "--set-xmark"
sslh  | Try `ip6tables -h' or 'ip6tables --help' for more information.
sslh  | + ip6tables -t mangle -A OUTPUT '!' -o lo -p tcp -m connmark --mark 0x01/0x0f -j CONNMARK --restore-mark --mask 0x0f
sslh  | modprobe: can't change directory to '/lib/modules': No such file or directory
sslh  | modprobe: can't change directory to '/lib/modules': No such file or directory
sslh  | modprobe: can't change directory to '/lib/modules': No such file or directory
sslh  | modprobe: can't change directory to '/lib/modules': No such file or directory
sslh  | modprobe: can't change directory to '/lib/modules': No such file or directory
sslh  | modprobe: can't change directory to '/lib/modules': No such file or directory
sslh  | ip6tables v1.8.9 (legacy): can't initialize ip6tables table `mangle': Table does not exist (do you need to insmod?)
sslh  | Perhaps ip6tables or your kernel needs to be upgraded.                                                                                                                                                     
sslh  | + ip6tables -t mangle -A POSTROUTING '!' -o lo -s ::1/128 -j DROP                                                                                                                                          
sslh  | modprobe: can't change directory to '/lib/modules': No such file or directory                                                                                                                              
sslh  | ip6tables v1.8.9 (legacy): can't initialize ip6tables table `mangle': Table does not exist (do you need to insmod?)                                                                                        
sslh  | Perhaps ip6tables or your kernel needs to be upgraded.                                                                                                                                                     
sslh  | + ip6tables -t nat -A OUTPUT -m owner --uid-owner sslh -p tcp --tcp-flags FIN,SYN,RST,ACK SYN -j CONNMARK --set-xmark 0x01/0x0f                                                                            
sslh  | modprobe: can't change directory to '/lib/modules': No such file or directory                                                                                                                              
sslh  | modprobe: can't change directory to '/lib/modules': No such file or directory
sslh  | modprobe: can't change directory to '/lib/modules': No such file or directory
sslh  | modprobe: can't change directory to '/lib/modules': No such file or directory
sslh  | modprobe: can't change directory to '/lib/modules': No such file or directory
sslh  | modprobe: can't change directory to '/lib/modules': No such file or directory
sslh  | ip6tables v1.8.9 (legacy): unknown option "--set-xmark"
sslh  | Try `ip6tables -h' or 'ip6tables --help' for more information.
sslh  | + ip6tables -t mangle -A OUTPUT '!' -o lo -p tcp -m connmark --mark 0x01/0x0f -j CONNMARK --restore-mark --mask 0x0f
sslh  | modprobe: can't change directory to '/lib/modules': No such file or directory
sslh  | modprobe: can't change directory to '/lib/modules': No such file or directory
sslh  | modprobe: can't change directory to '/lib/modules': No such file or directory
sslh  | modprobe: can't change directory to '/lib/modules': No such file or directory
sslh  | modprobe: can't change directory to '/lib/modules': No such file or directory
sslh  | modprobe: can't change directory to '/lib/modules': No such file or directory
sslh  | ip6tables v1.8.9 (legacy): can't initialize ip6tables table `mangle': Table does not exist (do you need to insmod?)
sslh  | Perhaps ip6tables or your kernel needs to be upgraded.
sslh  | + ip -6 rule add fwmark 0x1 lookup 100
sslh  | Executing with user 'sslh': sslh --transparent --foreground --listen=0.0.0.0:443 --tls=localhost:8080 --openvpn=localhost:8009 --ssh=localhost:22
sslh  | + ip -6 route add local ::/0 dev lo table 100
sslh  | + set -e
sslh  | + set +x
```
