### ISSUE TITLE
WORKING Transparent mode from SSLH on HOST to DOCKER container => but need help for improvments

### ISSUE THREAD

**Issue by f-vt** [yrutschle/sslh#411]
Hi,

I have actually found a way to make it works in transparent mode, inspired from this link: [https://superuser.com/questions/1326592/how-to-set-up-sslhs-transparent-mode-in-a-docker-environment](https://superuser.com/questions/1326592/how-to-set-up-sslhs-transparent-mode-in-a-docker-environment).

Tested with sslh from opensuse's repos (sslh-1.22c-2.6.x86_64) (fork version), and latest sslh compile from this git repo (fork & select version, both ok).

**I get SSLH running on HOST and forwarding TLS to DOCKER container (traefik reverse proxy), and SSH to the host's SSHD.**
- ![image](https://github.com/yrutschle/sslh/assets/16646471/fef103fe-017d-4ddb-9044-049e02246362)

I do not use the `--publish` option of docker which conflicts with SSLH rules, except for the 80 port which is still accessed directly, not through SSLH.
My "**traefik**" docker service is put on a dedicated overlay (should work with bridge also) network called "**proxy**" where it is alone, and in **DNRR** endpoint mode so that it will not be put behind a docker VIP (we don't want that IP appear only in the traefik access logs...).
So, as it is alone in the "**proxy**" network, it will 'almost' always take the `.2` IP address, but if you wish to use a hostname, you can try:
-  [https://www.linkedin.com/pulse/learn-how-access-docker-container-its-name-from-host-renato-rodrigues](https://www.linkedin.com/pulse/learn-how-access-docker-container-its-name-from-host-renato-rodrigues) )
- Or if you are using a versatile reverse proxy in a docker container, you can see my 1st comment in this issue to do it.

Traefik service is configured **internally** to listen on ports **80** and **443**. 
Having 443 is not a issue and will not conflicts with SSLH listener on Host IP, as it it not published on the host by docker but stay isolated in "**proxy**" network.
It must not be added to the iptables SSLH rules, as SSLH is talking to **traefik** "**proxy**" private docker vxnet IP like if it was talking to another host.

I use the **docker_gwbridge** docker gateway to access it from the Host (added a route to the "proxy" network where traefik is put; through this docker_gwbridge IP, on the host).
You don't need to change the OS kernel routing settings as this docker_gwbridge is already confgured to route local traffic:
![image](https://github.com/yrutschle/sslh/assets/16646471/ada8536e-81a5-4bd6-b4dc-96b150c634d8)

- My **traefik** docker configuration (swarm mode, but should work without swarm mode with few adaptations):
  ```yaml
  services:
    traefik:
      # The official v2.0 Traefik docker image
      image: traefik:latest
      # 2 replicas as critical service (needs to be in swarm mode)
      deploy:
        # to see real IP in logs: Mode global: one (and only one) service per node); to use with HOST networking (so that ports exposed on host through bridge network directly, bypassing mesh overlay. Only port 80 as 443 exposed through SSLH via docker_gwbridge
        mode: global
        # for not putting it behind docker mesh VIP and then seeing real client IPs in traefik logs instead VIP IP
        endpoint_mode: dnsrr
        placement:
          constraints:
            # Traefik instances needs to be scheduled on a manager node to get labels (this reduces availability for example in case the node fails (we'll need to wait for a redeploy on another node) but no other option yet)
            - "node.role==manager"
        restart_policy:
          condition: any
        update_config:
          parallelism: 1
          delay: 5s
          order: start-first
          monitor: 30s
          failure_action: rollback
      # Configure networks for traffic to endpoint to RP
      networks:
        - proxy
        - web_priv_services
        - web_devops_tools
        - security_services
      # Expose following ports to HOST IP (clients to RP)
      ports:
        # The HTTP port / HOST mode to see real IP in logs (to bypass overlay/mesh; combined with global deployment instruction)
        - target: 80
          published: 80
          protocol: tcp
          mode: host
        # HTTPS exposure handled by SSLH, and forwarded to container private ip in the "proxy" vxlan (added route on host using docker_gwbridge IP)
      environment:
        - "GANDIV5_API_KEY_FILE=/run/secrets/gandiv5_api_key"
        - LEGO_DISABLE_CNAME_SUPPORT=true # https://community.traefik.io/t/suddenly-experiencing-error-400-invalid-domain-errors-with-le-certs/16366/2 - IF YOU HAVE A WILDCARD CNAME for your DNS Zone - LEGO (backend program used by traefik for adding TXT entries through DNS provider API for automating letsencrypt DNS Challenge) can't check cname if a wildcard is present... Need to disable this  
        - TZ=Europe/Paris
        #- PUID=33 # Not handled by traefik container
        #- PGID=33 # Not handled by traefik container
      command:
        - '--api.dashboard=true' 
        #- '--api.insecure=true' don't needed, it exposes api on 8080, but we are using RP to api@internal not 8080.
        # Logs for Crowdsec
        - '--accesslog=true'
        # Docker provider
        - '--providers.docker'
        - '--providers.docker.endpoint=unix:///var/run/docker.sock'
        - '--providers.docker.watch=true'
        - '--providers.docker.exposedByDefault=false' # Warning: you needs to explicitely set "traefik.enable" flag label to true
        - '--providers.docker.swarmmode=false' # at the moment we use the docker socket, no need to use swarm mode
        # File provider
        - '--providers.file.directory=/traefik-dynamic-configs/'
        - '--providers.file.watch=true'
        # Entrypoints config
        - '--entrypoints.http=true'
        - '--entryPoints.http.address=:80'
        - '--entrypoints.https=true'
        - '--entryPoints.https.address=:443'
        # Entrypoints - http to https
        - '--entrypoints.http.http.redirections.entrypoint.to=https'
        - '--entrypoints.http.http.redirections.entrypoint.scheme=https'
        # CERT Resolver
        - '--certificatesresolvers.XXXXXXXXXX.acme.email=XXXXXXX@XXXX.XXX'
        #- '--certificatesresolvers.XXXXXXXXXX.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory' # letsencrypt staging/testing when needs debugging to not reach letsencrypt rate limit
        - '--certificatesresolvers.XXXXXXXXXX.acme.storage=/letsencrypt/acme.json'
        - '--certificatesresolvers.XXXXXXXXXX.acme.dnschallenge=true'
        - '--certificatesresolvers.XXXXXXXXXX.acme.dnschallenge.provider=gandiv5'
        - '--certificatesresolvers.XXXXXXXXXX.acme.dnschallenge.resolvers=217.70.177.40:53,173.246.100.219:53' # IMPORTANT: Put some Gandi's NS IP there. If not, letsencypt will have to wait A LOT OF TIME the DNS propagation (DNS challenge use in our case gandi API to create an entry in our DNS zone at our provider to validate ownership)
        # Enabling WAF module
        - '--experimental.plugins.traefik-modsecurity-plugin.modulename=github.com/madebymode/traefik-modsecurity-plugin'
        - '--experimental.plugins.traefik-modsecurity-plugin.version=v1.4.5'
      volumes:
        # Traefik certificate storage
        - traefik_letsencrypt:/letsencrypt/
        # Traefik dynamic config files (profider.file.directory)
        - traefik_dynconfig:/traefik-dynamic-configs/:ro
        # So that Traefik can listen to the Docker events
        - /var/run/docker.sock:/var/run/docker.sock:ro
      secrets:
        - gandiv5_api_key  
      labels:
        # GLOBAL - Auth
        - "traefik.http.middlewares.auth.basicauth.users=XXXXX:XXXXX" # use htpasswd to generate, double the $ signs
        # GLOBAL - Headers
        # Commented cause better conf below - 'traefik.http.middlewares.HSTS.headers.customresponseheaders.Strict-Transport-Security="max-age=6307200; includeSubDomains; preload"'
        - "traefik.http.middlewares.security-and-proxy-headers.headers.accessControlAllowOriginList=*"
        - "traefik.http.middlewares.security-and-proxy-headers.headers.AccessControlMaxAge=100"
        - "traefik.http.middlewares.security-and-proxy-headers.headers.BrowserXssFilter=true"
        - "traefik.http.middlewares.security-and-proxy-headers.headers.ContentTypeNosniff=true"
        - "traefik.http.middlewares.security-and-proxy-headers.headers.ForceSTSHeader=true"
        - "traefik.http.middlewares.security-and-proxy-headers.headers.FrameDeny=true"
        - "traefik.http.middlewares.security-and-proxy-headers.headers.SSLRedirect=true"
        - "traefik.http.middlewares.security-and-proxy-headers.headers.STSIncludeSubdomains=true"
        - "traefik.http.middlewares.security-and-proxy-headers.headers.STSPreload=true"
        - "traefik.http.middlewares.security-and-proxy-headers.headers.STSSeconds=63072000"
        - "traefik.http.middlewares.security-and-proxy-headers.headers.CustomFrameOptionsValue=SAMEORIGIN"
        - "traefik.http.middlewares.security-and-proxy-headers.headers.referrerPolicy=same-origin"
        # GLOBAL - Other
        - "traefik.http.middlewares.other.buffering.maxRequestBodyBytes=0"
        - "traefik.http.middlewares.other.buffering.memRequestBodyBytes=1000000000"
        - "traefik.http.middlewares.other.buffering.maxResponseBodyBytes=0"
        - "traefik.http.middlewares.other.buffering.memResponseBodyBytes=1000000000"
        - "traefik.http.middlewares.other.compress=false"
        # Endpoint Config
        - "traefik.enable=true"
        - "traefik.http.routers.api.entrypoints=https"
        - "traefik.http.routers.api.rule=Host(`XXXXXXXXXXX.XXX`)"
        - "traefik.http.routers.api.tls=true"
        - 'traefik.http.routers.api.tls.options=modern@file'
        - "traefik.http.routers.api.middlewares=auth,security-and-proxy-headers"
        - "traefik.http.routers.api.service=api@internal" # Assign api@internal who is pregenerated by traefik for itself to the api router, so nothing to configure for this, rewrites for api, etc. already defined.
        - "traefik.http.routers.api.tls.certresolver=xxxxxxxxx"
        - "traefik.http.routers.api.tls.domains[0].main=XXXXXXXXXXX.XXX"
        - "traefik.http.routers.api.tls.domains[0].sans=*.XXXXXXXXXXX.XXX"  # this wildcard cert will then be applied to all sites matching it
        # WAF enable (This is a very simple plugin that proxies the query to the owasp/modsecurity apache container, and checks in its answer if it has detected something in the query (>400 response) or not). Set max body size to inspect to 1GB.
        - traefik.http.middlewares.waf.plugin.traefik-modsecurity-plugin.modSecurityUrl=http://waf:80
        - traefik.http.middlewares.waf.plugin.traefik-modsecurity-plugin.maxBodySize=1073741824
        - traefik.http.middlewares.waf.plugin.traefik-modsecurity-plugin.cacheEnabled=true
  ```
- I put you there the content of the file configuration for SSL in case you want it:
  - ![image](https://github.com/yrutschle/sslh/assets/16646471/916f6c23-28c9-42f4-8db5-49f4cf22f857)

- The docker network "**proxy**":
  ```yaml
  networks:
    proxy:
      name: proxy
      driver: overlay
      ipam:
        driver: default
        config:
          - subnet:  "172.16.100.0/24"
  ```

- For debugging, to ensure that you don't have any firewalld drops if you use it, and see which traffic you need to allow in the logs:
  ```shell
  systemctl stop firewalld
  iptables -I INPUT -j LOG
  iptables -I INPUT -j ACCEPT
  ```
  - Note: Basically, as you are in transparent mode, you will need to allow all traffic as if it was flowing directly without SSLH in the middle:
    - Inbound traffic from ANY to SSLH (HOST IP, PORT TCP-443)
    - Inbound traffic from ANY to SSHD (HOST IP, PORT TCP-50022)
    - NO NEED TO ALLOW Inbound traffic to SSL  ("**proxy**" network IP range, PORT TCP-443), we are routing through docker_gwbridge, rules for this are managed by docker and OK 

- My SSLH config:
  ```shell
  # /etc/conf.d/sslh
  
  # Options to sslh itself. See the sslh(1) man page.
  #DAEMON_OPTS=""
  
  # Multiplexing example
  # Port 44 can be used for ssh, http, and https. Drop privileges after starting.
  # ssh: 192.168.10.250 as it's the only listening IP in the sshd config
  # tls: traefik container ip address in its standalone bridge/overlay network
  DAEMON_OPTS="-t 2 -p 192.168.10.250:443 --ssh 192.168.10.250:50022 --tls 172.16.100.2:443 --user sslh --transparent"
  ```

SSLH systemd service running status:
![image](https://github.com/yrutschle/sslh/assets/16646471/47cc4c11-8bd6-44d5-bdb9-e7ee9bc120ea)

- the SystemD sslh service config `/usr/lib/systemd/system/sslh.service` (not changed):
  ```shell
  [Unit]
  Description=SSL/SSH multiplexer
  After=network.target
  
  [Service]
  EnvironmentFile=/etc/conf.d/sslh
  ExecStart=/usr/sbin/sslh --foreground $DAEMON_OPTS
  KillMode=process
  #Hardening
  PrivateTmp=true
  CapabilityBoundingSet=CAP_NET_BIND_SERVICE
  AmbientCapabilities=CAP_NET_BIND_SERVICE
  SecureBits=noroot-locked
  ProtectSystem=strict
  ProtectHome=true
  ProtectKernelModules=true
  ProtectKernelTunables=true
  ProtectControlGroups=true
  MountFlags=private
  NoNewPrivileges=true
  PrivateDevices=true
  RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX
  MemoryDenyWriteExecute=true
  DynamicUser=true
  
  [Install]
  WantedBy=multi-user.target
  ```

- the SystemD sslh service override for the needed CAP_NET_ADMIN addition for transparent mode `/etc/systemd/system/sslh.service.d/setcap_overrides.conf`  (not sure I need ADMIN in both but didn't had time to test):
 ```shell
  [Service]
  CapabilityBoundingSet=CAP_NET_BIND_SERVICE, CAP_NET_ADMIN
  AmbientCapabilities=CAP_NET_BIND_SERVICE, CAP_NET_ADMIN
  ```

- the SystemD sslh service override for the pre start and post stop actions, adding the route to docker "proxy" network where my reverse proxy belongs to, and adding iptables rules for SSH to HOST's SSHD `/etc/systemd/system/sslh.service.d/exec_actions.conf` :
  ```shell
  [Service]
  # Exec commands will run with full permissions by using the "+" (https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html#Command%20lines), so we don't have to add families access permissions, docker socket permission, ... for ExecStartPost and ExecStop commands. sslh ExecStart defines in the sslh.service root configuration will well have all the restriction applied.
  
  #ExecStartPost=+iptables -t nat -A OUTPUT -m owner --uid-owner sslh -p tcp --tcp-flags FIN,SYN,RST,ACK SYN -j CONNMARK --set-xmark 0x01/0x0f
  #ExecStartPost=+iptables -t mangle -A OUTPUT ! -o lo -p tcp -m connmark --mark 0x01/0x0f -m tcp --sport 50022 -j CONNMARK --restore-mark --mask 0x0f
  ExecStartPost=+iptables -t mangle -N SSLH
  ExecStartPost=+iptables -t mangle -A PREROUTING -p tcp -m socket --transparent -j SSLH
  ExecStartPost=+iptables -t mangle -A OUTPUT -p tcp -m tcp --sport 50022 -j SSLH
  ExecStartPost=+iptables -t mangle -A SSLH --jump MARK --set-mark 0x1
  ExecStartPost=+iptables -t mangle -A SSLH --jump ACCEPT
  ExecStartPost=+ip rule add fwmark 0x1 lookup 100
  ExecStartPost=+ip route add local 0.0.0.0/0 dev lo table 100
  ExecStartPost=+bash -c 'ip route add $$(docker network inspect proxy --format "{{(index .IPAM.Config 0).Subnet}}") via $$(docker network inspect docker_gwbridge --format "{{(index .IPAM.Config 0).Gateway}}")'
  
  #ExecStopPost=+iptables -t nat -D OUTPUT -m owner --uid-owner sslh -p tcp --tcp-flags FIN,SYN,RST,ACK SYN -j CONNMARK --set-xmark 0x01/0x0f
  #ExecStopPost=+iptables -t mangle -D OUTPUT ! -o lo -p tcp -m connmark --mark 0x01/0x0f -m tcp --sport 50022 -j CONNMARK --restore-mark --mask 0x0f
  ExecStopPost=+iptables -t mangle -D OUTPUT -p tcp -m tcp --sport 50022 -j SSLH
  ExecStopPost=+iptables -t mangle -D PREROUTING -p tcp -m socket --transparent -j SSLH
  ExecStopPost=+iptables -t mangle -F SSLH
  ExecStopPost=+iptables -t mangle -X SSLH
  ExecStopPost=+ip rule del fwmark 0x1 lookup 100
  ExecStopPost=+ip route del local 0.0.0.0/0 dev lo table 100
  ExecStopPost=+bash -c 'ip route del $$(docker network inspect proxy --format "{{(index .IPAM.Config 0).Subnet}}") via $$(docker network inspect docker_gwbridge --format "{{(index .IPAM.Config 0).Gateway}}")'
  ```

Unfortunately, I was not able to find a way to add a `-m owner --uid-owner sslh` filter so when SSLH starts it breaks the direct connection to the original SSHD port (50022) and you are forced to connects to SSHD through SSLH (port 443) from you SSH client... 
If I add this `-m owner --uid-owner sslh`to the rule `iptables -t mangle -A OUTPUT -p tcp -m tcp --sport 50022 -j SSLH` then the rule stops matching the traffic, so SSH access stops working.
If I use the rules below (I can only add a filter --sport 50022 in the mangle part, if I put it in the nat one it breaks SSH, no traffic matchs) :
```bash
ExecStartPost=+iptables -t nat -A OUTPUT -m owner --uid-owner sslh -p tcp --tcp-flags FIN,SYN,RST,ACK SYN -j CONNMARK --set-xmark 0x01/0x0f
ExecStartPost=+iptables -t mangle -A OUTPUT ! -o lo -p tcp -m connmark --mark 0x01/0x0f -m tcp --sport 50022 -j 
```
Then SSL stops working as the NAT rules marks the SSL traffic too, and it should not be touched. These rules should only match SSH (50022) traffic and for sslh user only..
**If someone knows how to do it would be very great as it is not very practical to have SSLH blocking direct access on proxied Host services.**

Note: after SSLH service started, you may have to wait 1-2 minutes before routes are taken in account and the TLS endpoint works:
![image](https://github.com/yrutschle/sslh/assets/16646471/047c084c-6182-4931-b300-7cc7328bac3e)
![image](https://github.com/yrutschle/sslh/assets/16646471/01d1f35f-cc5f-4ba4-b3ef-021a11d5cb4e)
