### ISSUE TITLE
Bug: Proxy Protocol Destination IP/Port Incorrectly Set to Backend Details

### ISSUE THREAD

**Issue by 4O4-Not-F0und** [yrutschle/sslh#496]
**Description:**

When using Proxy Protocol to pass client connection information to the backend, the destination IP address and port in the Proxy Protocol header are being set to the IP address and port of the backend server itself, rather than the original IP address and port the client connected to at the sslh.

This behavior is incorrect as the purpose of these fields in the Proxy Protocol header is to convey the *original* destination address the client intended to reach.

**Steps to Reproduce:**

In this case, the architect is:

```
Client (172.21.0.1:Port_C) ---> SSLH (172.21.0.2:20000) ---> Socat (172.21.0.3:12345)
```

* Compile sslh with proxyprotocol support
* Use environment below
* `telnet 172.21.0.2 20000`
* Will see proxyprotocol data in echoback text

---

**Environment for Reproduction:**

Docker Compose:

```yaml
services:
  sslh:
    # Compiled sslh with proxyprotocol support
    image: sslh-with-proxyprotocol:latest
    container_name: sslh
    command:
      - --config
      - /etc/sslh.cfg
    volumes:
      - "./sslh.cfg:/etc/sslh.cfg:ro"
    ports:
      - 20000:20000/tcp
    restart: unless-stopped

  # Just a echoback server
  socat:
    image: alpine/socat
    container_name: socat
    command: TCP-LISTEN:12345,fork,reuseaddr EXEC:'cat'
    restart: unless-stopped
```

sslh config:

```
foreground: true;

listen: (
    { host: "0.0.0.0"; port: "20000"; }
);

protocols: (
    {
        name: "anyprot";
        host: "socat";
        port: "12345";
        proxyprotocol: 1;
        log_level: 1;
    }
);
```

**Expected Behavior:**

The Proxy Protocol header should contain:
* `Destination IP`: The IP address of sslh. (`172.21.0.2`)
* `Destination Port`: The port of sslh. (`20000`)

**Actual Behavior:**

The Proxy Protocol header contains:
* `Destination IP`: The IP address of the backend server. (`172.21.0.3`)
* `Destination Port`: The port of the backend server. (`12345`)

Packet Capture:

![Image](https://github.com/user-attachments/assets/ee237ee5-e706-4f7b-9a14-549c89a779d0)

telnet echoback:

![Image](https://github.com/user-attachments/assets/71e4c4f9-24e4-475b-bd41-b0ec76852e74)
